import type { SubOrder, QueueItem, Notification, User, Vendor, VendorRFQ } from './types'

// ─── Current User ─────────────────────────────────────────────────────────────

export const currentUser: User = {
  id: 'u1',
  name: 'Parthipan Kumar',
  initials: 'PK',
  role: 'sourcing-poc',
  brand: 'Nautinati',
  email: 'parthipan@tmrw.com',
}

// ─── Vendors ──────────────────────────────────────────────────────────────────

export const vendors: Vendor[] = [
  { id: 'v1',  name: 'BHARTI APPARELS',     location: 'FARIDABAD', otifScore: 74, fiPassRate: 82, tier: 'Tier 1', contactName: 'Rajiv Bharti',    contactPhone: '+91 98100 11001', contactEmail: 'rajiv@bhartiapparels.com' },
  { id: 'v2',  name: 'ARIHANT FASHIONS',    location: 'KOLKATA',   otifScore: 61, fiPassRate: 88, tier: 'Tier 2', contactName: 'Sunita Arihant',   contactPhone: '+91 98300 22002', contactEmail: 'sunita@arihantfashions.com' },
  { id: 'v3',  name: 'IDS FASHION',         location: 'NOIDA',     otifScore: 55, fiPassRate: 78, tier: 'Tier 3', contactName: 'Deepak Sharma',    contactPhone: '+91 99100 33003', contactEmail: 'deepak@idsfashion.com' },
  { id: 'v4',  name: 'BS FASHION',          location: 'KOLKATA',   otifScore: 80, fiPassRate: 91, tier: 'Tier 1', contactName: 'Baldev Singh',     contactPhone: '+91 98300 44004', contactEmail: 'baldev@bsfashion.com' },
  { id: 'v5',  name: 'DIV CREATIONS',       location: 'FARIDABAD', otifScore: 68, fiPassRate: 85, tier: 'Tier 2', contactName: 'Divya Kapoor',     contactPhone: '+91 98100 55005', contactEmail: 'divya@divcreations.com' },
  { id: 'v6',  name: 'AND DESIGN',          location: 'JAIPUR',    otifScore: 72, fiPassRate: 84, tier: 'Tier 1', contactName: 'Anand Mehta',      contactPhone: '+91 94100 66006', contactEmail: 'anand@anddesign.com' },
  { id: 'v7',  name: 'ADITEE INTERNATIONAL',location: 'JAIPUR',    otifScore: 63, fiPassRate: 79, tier: 'Tier 2', contactName: 'Aditi Verma',      contactPhone: '+91 94100 77007', contactEmail: 'aditi@aditeeintl.com' },
  { id: 'v8',  name: 'CAARVI TEXTILES',     location: 'DELHI',     otifScore: 77, fiPassRate: 87, tier: 'Tier 1', contactName: 'Caarvika Nair',    contactPhone: '+91 98110 88008', contactEmail: 'caarvika@caarvitextiles.com' },
  { id: 'v9',  name: 'PESOS VISION',        location: 'MUMBAI',    otifScore: 70, fiPassRate: 83, tier: 'Tier 2', contactName: 'Prashant Soman',   contactPhone: '+91 98200 99009', contactEmail: 'prashant@pesosvision.com' },
  { id: 'v10', name: 'SWARA CREATION',      location: 'SURAT',     otifScore: 65, fiPassRate: 76, tier: 'Tier 2', contactName: 'Swara Patel',      contactPhone: '+91 94260 10010', contactEmail: 'swara@swaracreation.com' },
]

// ─── SubOrders ────────────────────────────────────────────────────────────────

export const subOrders: SubOrder[] = [
  {
    id: 'NNKNTW250001',
    styleCode: 'NN401-238',
    styleName: 'Girls Printed Cotton Dress',
    colour: 'CORAL',
    category: 'Knits',
    product: 'Dress',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '2-8 Y',
    fabricQuality: 'Printed Cotton Flex / Rayon Twill',
    vendor: vendors[0],
    poc: currentUser,
    status: 'overdue',
    currentStage: 'production',
    atRisk: true,
    handoverDate: '2026-03-08',
    orderToVendorDate: '2026-03-15',
    buyingExpectedInwardDate: '2026-04-28',
    vendorPromisedDate: '2026-04-25',
    costingApprovedDate: '2026-03-22',
    targetPrice: 285,
    closedCost: 272,
    costStatus: 'approved',
    orderQty: 500,
    cutQty: 360,
    sewingQty: 290,
    packedQty: 0,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0612M', qty: 200 },
      { warehouse: 'GUR', poNumber: 'PPO-0612S', qty: 150 },
      { warehouse: 'BLR', poNumber: 'PPO-0612B', qty: 150 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-04-01', actualDate: '2026-04-03', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-04-05', actualDate: '2026-04-06', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-04-08', actualDate: '2026-04-09', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-04-10', actualDate: '2026-04-11', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-04-12', actualDate: '2026-04-13', approvedBy: 'Priya M + Rahul K', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-04-13', actualDate: '2026-04-14', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-14', actualDate: '2026-04-14', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
    ],
    productionHistory: [
      { date: '2026-04-12', cutQty: 360, sewingQty: 290, packedQty: 0, updatedBy: 'Parthipan Kumar', onBehalfOf: 'Bharti Apparels' },
      { date: '2026-04-10', cutQty: 320, sewingQty: 240, packedQty: 0, updatedBy: 'Bharti Apparels' },
      { date: '2026-04-08', cutQty: 280, sewingQty: 190, packedQty: 0, updatedBy: 'Bharti Apparels' },
      { date: '2026-04-05', cutQty: 200, sewingQty: 120, packedQty: 0, updatedBy: 'Bharti Apparels' },
    ],
    fiRequests: [],
    samples: [
      { id: 's1', type: 'Proto', round: 1, dispatchDate: '2026-03-18', receivedDate: '2026-03-20', sentTo: 'Priya M (Designer)', courier: 'DTDC', trackingNo: 'DTDC-8821001', qty: 2, status: 'rejected', comments: 'Silhouette too boxy — waist needs definition', revisionNotes: 'Reduce width at waist by 1.5cm, adjust armhole curve' },
      { id: 's2', type: 'Fit Sample', round: 1, dispatchDate: '2026-03-26', receivedDate: '2026-03-28', sentTo: 'Rahul K (Fit Technician)', courier: 'DTDC', trackingNo: 'DTDC-8831012', qty: 3, status: 'approved', comments: 'Fit excellent — approved to proceed', approvedBy: 'Rahul K', approvedDate: '2026-03-28' },
      { id: 's3', type: 'PP Sample', round: 1, dispatchDate: '2026-04-10', receivedDate: '2026-04-12', sentTo: 'Priya M + Rahul K', courier: 'FedEx', trackingNo: 'FX-9920443', qty: 4, status: 'approved', comments: 'Colour, construction, and fit all approved for bulk', approvedBy: 'Priya M + Rahul K', approvedDate: '2026-04-13' },
    ],
    history: [
      { id: 'h1', timestamp: '2026-04-12T14:32:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Production qty updated', details: 'Cut 320→360, Sewing 240→290', onBehalfOf: 'Bharti Apparels' },
      { id: 'h2', timestamp: '2026-04-14T09:15:00', actor: 'Rahul K', actorRole: 'Fit Technician', action: 'PP Fit approved', details: 'Fit approved — production cleared' },
      { id: 'h3', timestamp: '2026-04-13T11:20:00', actor: 'Priya M + Rahul K', actorRole: 'Designer + Fit Tech', action: 'PP Sample (4B) approved' },
      { id: 'h4', timestamp: '2026-04-11T16:45:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Fabric Inward confirmed' },
      { id: 'h5', timestamp: '2026-03-22T10:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹272 ≤ ₹285 target' },
      { id: 'h6', timestamp: '2026-03-15T09:30:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'Bharti Apparels, Faridabad' },
      { id: 'h7', timestamp: '2026-03-10T11:00:00', actor: 'Ahul Singh', actorRole: 'Sourcing Manager', action: 'SubOrder assigned to Parthipan Kumar' },
      { id: 'h8', timestamp: '2026-03-08T14:20:00', actor: 'Megha Sharma', actorRole: 'Category Head', action: 'Order Brief created' },
    ],
  },
  {
    id: 'NNKNTW250002',
    styleCode: 'NN413-185',
    styleName: 'Girls Woven Co-ord Set',
    colour: 'BLUE WHITE',
    category: 'Knits',
    product: 'Co-ords',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Poplin / Poly Crepe',
    vendor: vendors[1],
    poc: currentUser,
    status: 'overdue',
    currentStage: 'pre-prod',
    atRisk: true,
    handoverDate: '2026-03-12',
    orderToVendorDate: '2026-03-20',
    buyingExpectedInwardDate: '2026-05-05',
    vendorPromisedDate: '2026-05-02',
    costingApprovedDate: '2026-03-28',
    targetPrice: 310,
    closedCost: 295,
    costStatus: 'approved',
    orderQty: 300,
    cutQty: 0,
    sewingQty: 0,
    packedQty: 0,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0620M', qty: 150 }, { warehouse: 'GUR', poNumber: 'PPO-0620S', qty: 150 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-04-02', actualDate: '2026-04-04', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-04-06', actualDate: '2026-04-07', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-04-09', actualDate: '2026-04-10', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-04-11', actualDate: '2026-04-12', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'overdue', plannedDate: '2026-04-10', approvedBy: undefined, approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'not-started', plannedDate: '2026-04-18', approvedBy: undefined, approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'not-started', plannedDate: '2026-04-20', approvedBy: undefined, approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    samples: [
      { id: 's1', type: 'Proto', round: 1, dispatchDate: '2026-03-22', receivedDate: '2026-03-24', sentTo: 'Priya M (Designer)', courier: 'DTDC', trackingNo: 'DTDC-9001234', qty: 2, status: 'revision-requested', comments: 'Fabric drape acceptable but neckline needs rework', revisionNotes: 'Deepen neckline by 1cm, reduce collar stand height' },
      { id: 's2', type: 'Fit Sample', round: 1, dispatchDate: '2026-04-02', receivedDate: '2026-04-04', sentTo: 'Rahul K (Fit Technician)', courier: 'DTDC', trackingNo: 'DTDC-9005678', qty: 3, status: 'approved', comments: 'Fit approved, proceed to PP Sample', approvedBy: 'Rahul K', approvedDate: '2026-04-04' },
      { id: 's3', type: 'PP Sample', round: 1, dispatchDate: '2026-04-15', sentTo: 'Priya M + Rahul K', courier: 'FedEx', qty: 4, status: 'dispatched', comments: '' },
    ],
    history: [
      { id: 'h1', timestamp: '2026-04-10T10:00:00', actor: 'Rahul K', actorRole: 'Fit Technician', action: 'Fit Sample approved' },
      { id: 'h2', timestamp: '2026-03-28T09:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹295 ≤ ₹310 target' },
    ],
  },
  {
    id: 'NNKNTW250003',
    styleCode: 'NN321-099',
    styleName: 'Boys Cotton Shorts Set',
    colour: 'YELLOW',
    category: 'Knits',
    product: 'Clothing Set',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Boys',
    ageGroup: '1-5 Y',
    fabricQuality: 'Cotton Twill / Pique',
    vendor: vendors[2],
    poc: currentUser,
    status: 'overdue',
    currentStage: 'fi',
    atRisk: true,
    handoverDate: '2026-02-28',
    orderToVendorDate: '2026-03-08',
    buyingExpectedInwardDate: '2026-04-22',
    vendorPromisedDate: '2026-04-20',
    costingApprovedDate: '2026-03-15',
    targetPrice: 265,
    closedCost: 258,
    costStatus: 'approved',
    orderQty: 400,
    cutQty: 400,
    sewingQty: 390,
    packedQty: 385,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0605M', qty: 200 }, { warehouse: 'GUR', poNumber: 'PPO-0605S', qty: 120 }, { warehouse: 'BLR', poNumber: 'PPO-0605B', qty: 80 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-15', actualDate: '2026-03-16', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-03-18', actualDate: '2026-03-19', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-03-22', actualDate: '2026-03-23', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-03-25', actualDate: '2026-03-26', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-03-28', actualDate: '2026-03-30', approvedBy: 'Priya M + Rahul K', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-03-31', actualDate: '2026-04-01', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-02', actualDate: '2026-04-02', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
    ],
    productionHistory: [
      { date: '2026-04-13', cutQty: 400, sewingQty: 390, packedQty: 385, updatedBy: 'IDS Fashion' },
      { date: '2026-04-10', cutQty: 380, sewingQty: 360, packedQty: 300, updatedBy: 'IDS Fashion' },
    ],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-13T16:00:00', actor: 'IDS Fashion', actorRole: 'Vendor', action: 'Production qty updated', details: 'Packed 300→385' },
      { id: 'h2', timestamp: '2026-04-02T10:00:00', actor: 'Rahul K', actorRole: 'Fit Technician', action: 'PP Fit approved' },
    ],
  },
  {
    id: 'NNKNTW250004',
    styleCode: 'NN411-715',
    styleName: 'Girls Party Dress',
    colour: 'PINK',
    category: 'Knits',
    product: 'Dress',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'HERO',
    gender: 'Girls',
    ageGroup: '0-3 Y',
    fabricQuality: 'Poly Net / Satin',
    vendor: vendors[3],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'pre-prod',
    atRisk: false,
    handoverDate: '2026-03-20',
    orderToVendorDate: '2026-03-28',
    buyingExpectedInwardDate: '2026-05-10',
    vendorPromisedDate: '2026-05-08',
    costingApprovedDate: '2026-04-02',
    targetPrice: 350,
    closedCost: 338,
    costStatus: 'approved',
    orderQty: 350,
    cutQty: 0,
    sewingQty: 0,
    packedQty: 0,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0625M', qty: 200 }, { warehouse: 'GUR', poNumber: 'PPO-0625S', qty: 150 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'pending', plannedDate: '2026-04-14', approvedBy: undefined, approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'not-started', plannedDate: '2026-04-18', approvedBy: undefined, approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'not-started', plannedDate: '2026-04-22', approvedBy: undefined, approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'not-started', plannedDate: '2026-04-25', approvedBy: undefined, approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'not-started', plannedDate: '2026-04-28', approvedBy: undefined, approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'not-started', plannedDate: '2026-04-30', approvedBy: undefined, approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'not-started', plannedDate: '2026-05-02', approvedBy: undefined, approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    history: [{ id: 'h1', timestamp: '2026-04-02T09:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹338 ≤ ₹350 target' }],
  },
  {
    id: 'NNKNTW250005',
    styleCode: 'NN413-438',
    styleName: 'Girls Skirt Set',
    colour: 'GREEN',
    category: 'Knits',
    product: 'Skirt Set',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Printed Cotton Poplin',
    vendor: vendors[4],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'costing',
    atRisk: false,
    handoverDate: '2026-03-25',
    orderToVendorDate: '2026-04-02',
    buyingExpectedInwardDate: '2026-05-15',
    vendorPromisedDate: '2026-05-12',
    targetPrice: 285,
    closedCost: undefined,
    costStatus: 'pending',
    orderQty: 250,
    cutQty: 0,
    sewingQty: 0,
    packedQty: 0,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    history: [{ id: 'h1', timestamp: '2026-04-02T14:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'DIV Creations, Faridabad' }],
  },
  {
    id: 'NNKNTW250006',
    styleCode: 'NN401-802',
    styleName: 'Girls Ethnic Kurta Set',
    colour: 'WHITE',
    category: 'Wovens',
    product: 'Ethnic',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '2-8 Y',
    fabricQuality: 'Cotton Cambric / Georgette',
    vendor: vendors[5],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'production',
    atRisk: false,
    handoverDate: '2026-03-10',
    orderToVendorDate: '2026-03-18',
    buyingExpectedInwardDate: '2026-04-30',
    vendorPromisedDate: '2026-04-28',
    costingApprovedDate: '2026-03-25',
    targetPrice: 420,
    closedCost: 398,
    costStatus: 'approved',
    orderQty: 450,
    cutQty: 280,
    sewingQty: 210,
    packedQty: 0,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0608M', qty: 250 }, { warehouse: 'GUR', poNumber: 'PPO-0608S', qty: 200 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-28', actualDate: '2026-03-29', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-04-01', actualDate: '2026-04-02', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-04-04', actualDate: '2026-04-05', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-04-06', actualDate: '2026-04-07', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-04-08', actualDate: '2026-04-09', approvedBy: 'Priya M + Rahul K', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-04-10', actualDate: '2026-04-10', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-11', actualDate: '2026-04-11', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
    ],
    productionHistory: [
      { date: '2026-04-13', cutQty: 280, sewingQty: 210, packedQty: 0, updatedBy: 'AND DESIGN' },
      { date: '2026-04-11', cutQty: 220, sewingQty: 160, packedQty: 0, updatedBy: 'AND DESIGN' },
    ],
    fiRequests: [],
    history: [],
  },
  // On-track SubOrders
  {
    id: 'NNKNTW250009',
    styleCode: 'NN413-305',
    styleName: 'Girls Coord Set Checks',
    colour: 'MULTI',
    category: 'Knits',
    product: 'Co-ords',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Checks / Denim',
    vendor: vendors[8],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'fi',
    atRisk: false,
    handoverDate: '2026-02-20',
    orderToVendorDate: '2026-03-01',
    buyingExpectedInwardDate: '2026-04-25',
    vendorPromisedDate: '2026-04-23',
    costingApprovedDate: '2026-03-08',
    targetPrice: 295,
    closedCost: 282,
    costStatus: 'approved',
    orderQty: 350,
    cutQty: 350,
    sewingQty: 345,
    packedQty: 320,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0598M', qty: 180 }, { warehouse: 'GUR', poNumber: 'PPO-0598S', qty: 170 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-10', actualDate: '2026-03-11', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-03-14', actualDate: '2026-03-15', approvedBy: 'Priya M', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-03-18', actualDate: '2026-03-19', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-03-20', actualDate: '2026-03-21', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-03-24', actualDate: '2026-03-25', approvedBy: 'Priya M + Rahul K', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT', status: 'approved', plannedDate: '2026-03-26', actualDate: '2026-03-26', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-03-28', actualDate: '2026-03-28', approvedBy: 'Rahul K', approverRole: 'Fit Technician' },
    ],
    productionHistory: [{ date: '2026-04-13', cutQty: 350, sewingQty: 345, packedQty: 320, updatedBy: 'PESOS VISION' }],
    fiRequests: [],
    history: [],
  },
  {
    id: 'NNKNTW250040',
    styleCode: 'NN440-302',
    styleName: 'Girls Embroidered Kurti Set',
    colour: 'DUSTY ROSE',
    category: 'Wovens',
    product: 'Kurta Set',
    season: 'AW26',
    orderType: 'NEW',
    tier: 'HERO',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Cambric 60x60',
    vendor: vendors[0],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'pre-prod',
    atRisk: true,
    handoverDate: '2026-04-10',
    orderToVendorDate: '2026-04-15',
    buyingExpectedInwardDate: '2026-07-10',
    vendorPromisedDate: '2026-07-08',
    targetPrice: 465,
    costStatus: 'approved',
    closedCost: 448,
    costingApprovedDate: '2026-04-20',
    orderQty: 540,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0780M', qty: 200 },
      { warehouse: 'GUR', poNumber: 'PPO-0780S', qty: 180 },
      { warehouse: 'BLR', poNumber: 'PPO-0780B', qty: 160 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip',                        status: 'approved',     plannedDate: '2026-04-18', actualDate: '2026-04-19', approvedBy: 'Priya M',          approverRole: 'Designer'           },
      { id: 'pp2', name: 'Strike Off',                     status: 'approved',     plannedDate: '2026-04-22', actualDate: '2026-04-23', approvedBy: 'Priya M',          approverRole: 'Designer'           },
      { id: 'pp3', name: 'Fit Sample',                     status: 'pending',      plannedDate: '2026-04-28',                                                          approverRole: 'Fit Technician'     },
      { id: 'pp4', name: 'Fabric Inward (FD Status)',      status: 'not-started',  plannedDate: '2026-05-02',                                                          approverRole: 'POC'                },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)',    status: 'not-started',  plannedDate: '2026-05-08',                                                          approverRole: 'Designer + Fit Tech'},
      { id: 'pp6', name: 'GPT (Garment Processing Test)',  status: 'not-started',  plannedDate: '2026-05-12',                                                          approverRole: 'POC'                },
      { id: 'pp7', name: 'PP Fit',                         status: 'not-started',  plannedDate: '2026-05-15',                                                          approverRole: 'Fit Technician'     },
    ],
    productionHistory: [],
    fiRequests: [],
    samples: [
      { id: 's1', type: 'Proto',      round: 1, dispatchDate: '2026-04-17', receivedDate: '2026-04-19', sentTo: 'Priya M (Designer)',           courier: 'DTDC',  trackingNo: 'DTDC-1120045', qty: 2, status: 'revision-requested', comments: 'Embroidery placement needs to move 2cm up. Neckline binding width reduce to 1cm.', revisionNotes: 'Move chest embroidery up by 2cm; reduce neckline binding to 1cm' },
      { id: 's2', type: 'Fit Sample', round: 1, dispatchDate: '2026-04-26', sentTo: 'Rahul K (Fit Technician)',                                  courier: 'FedEx', trackingNo: 'FX-7741820',   qty: 3, status: 'dispatched', comments: '' },
    ],
    history: [
      { id: 'h1', timestamp: '2026-04-23T11:00:00', actor: 'Priya M',          actorRole: 'Designer',       action: 'Strike Off approved'                                                   },
      { id: 'h2', timestamp: '2026-04-19T10:00:00', actor: 'Priya M',          actorRole: 'Designer',       action: 'Proto sample revision requested', details: 'Move embroidery 2cm up'    },
      { id: 'h3', timestamp: '2026-04-20T09:00:00', actor: 'Parthipan Kumar',  actorRole: 'Sourcing POC',   action: 'Costing approved at ₹448'                                             },
    ],
  },
  {
    id: 'NNKNTW250011',
    styleCode: 'NN311-067',
    styleName: 'Girls Top and Bottom Set',
    colour: 'MAROON',
    category: 'Knits',
    product: 'Top and Bottom',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '0-3 Y',
    fabricQuality: 'Rayon Twill / Cotton Voile',
    vendor: vendors[0],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'asn',
    atRisk: false,
    handoverDate: '2026-02-10',
    orderToVendorDate: '2026-02-18',
    buyingExpectedInwardDate: '2026-04-20',
    vendorPromisedDate: '2026-04-18',
    costingApprovedDate: '2026-02-25',
    targetPrice: 250,
    closedCost: 238,
    costStatus: 'approved',
    orderQty: 300,
    cutQty: 305,
    sewingQty: 302,
    packedQty: 298,
    fiQty: 295,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0580M', qty: 160 }, { warehouse: 'GUR', poNumber: 'PPO-0580S', qty: 140 }],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [
      { id: 'fi1', requestedDate: '2026-04-10', scheduledDate: '2026-04-11', assignedInspector: 'Nimain Das', status: 'pass', fiQty: 295, location: 'Faridabad Factory', result: 'pass', round: 1 },
    ],
    history: [],
  },
  {
    id: 'NNKNTW250012',
    styleCode: 'NN413-009',
    styleName: 'Girls Party Wear Dress',
    colour: 'ORANGE',
    category: 'Knits',
    product: 'Dress',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '0-3 Y',
    fabricQuality: 'Poly Satin / Net',
    vendor: vendors[1],
    poc: currentUser,
    status: 'completed',
    currentStage: 'grn',
    atRisk: false,
    handoverDate: '2026-01-20',
    orderToVendorDate: '2026-01-28',
    buyingExpectedInwardDate: '2026-04-15',
    vendorPromisedDate: '2026-04-12',
    costingApprovedDate: '2026-02-05',
    targetPrice: 380,
    closedCost: 362,
    costStatus: 'approved',
    orderQty: 400,
    cutQty: 408,
    sewingQty: 405,
    packedQty: 395,
    fiQty: 390,
    dispatchedQty: 390,
    grnQty: 390,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0565M', qty: 220 }, { warehouse: 'GUR', poNumber: 'PPO-0565S', qty: 180 }],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip',                       status: 'approved', plannedDate: '2026-02-08', actualDate: '2026-02-10', approvedBy: 'Priya M',          approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off',                     status: 'approved', plannedDate: '2026-02-14', actualDate: '2026-02-15', approvedBy: 'Priya M',          approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample',                     status: 'approved', plannedDate: '2026-02-20', actualDate: '2026-02-22', approvedBy: 'Rahul K',          approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)',      status: 'approved', plannedDate: '2026-02-25', actualDate: '2026-02-26', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)',    status: 'approved', plannedDate: '2026-03-02', actualDate: '2026-03-04', approvedBy: 'Priya M + Rahul K', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-03-06', actualDate: '2026-03-07', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit',                         status: 'approved', plannedDate: '2026-03-09', actualDate: '2026-03-09', approvedBy: 'Rahul K',          approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [{ id: 'fi1', requestedDate: '2026-04-05', scheduledDate: '2026-04-06', assignedInspector: 'Rishabh Sharma', status: 'pass', fiQty: 390, result: 'pass', round: 1 }],
    history: [],
  },
  {
    id: 'NNKNTW250014',
    styleCode: 'NN311-715',
    styleName: 'Boys Clothing Set',
    colour: 'GREY',
    category: 'Knits',
    product: 'Clothing Set',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'HERO',
    gender: 'Boys',
    ageGroup: '1-5 Y',
    fabricQuality: 'Cotton Flex / Chambray',
    vendor: vendors[3],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'production',
    atRisk: false,
    handoverDate: '2026-03-05',
    orderToVendorDate: '2026-03-12',
    buyingExpectedInwardDate: '2026-05-05',
    vendorPromisedDate: '2026-05-03',
    costingApprovedDate: '2026-03-20',
    targetPrice: 320,
    closedCost: 308,
    costStatus: 'approved',
    orderQty: 500,
    cutQty: 420,
    sewingQty: 380,
    packedQty: 310,
    fiQty: 0,
    dispatchedQty: 0,
    grnQty: 0,
    poNumbers: [{ warehouse: 'MUM', poNumber: 'PPO-0615M', qty: 280 }, { warehouse: 'GUR', poNumber: 'PPO-0615S', qty: 220 }],
    preProdStages: [],
    productionHistory: [{ date: '2026-04-13', cutQty: 420, sewingQty: 380, packedQty: 310, updatedBy: 'BS Fashion' }],
    fiRequests: [],
    history: [],
  },
  // ── Lifecycle Stage: Order Brief (Vendor Not Assigned) ───────────────────────
  {
    id: 'NNKNTW250020',
    styleCode: 'NN415-201',
    styleName: 'Boys Printed Graphic Tee',
    colour: 'NAVY BLUE',
    category: 'Knits',
    product: 'Top',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Boys',
    ageGroup: '2-8 Y',
    fabricQuality: 'Printed Cotton Jersey',
    vendor: { id: 'v_tba', name: 'NOT ASSIGNED', location: '—' } as any,
    poc: currentUser,
    status: 'not-started',
    currentStage: 'order-brief',
    atRisk: false,
    handoverDate: '2026-04-10',
    orderToVendorDate: '2026-04-20',
    buyingExpectedInwardDate: '2026-06-15',
    vendorPromisedDate: '2026-06-10',
    targetPrice: 180,
    costStatus: 'pending',
    orderQty: 600,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-10T10:00:00', actor: 'Megha Sharma', actorRole: 'Category Head', action: 'Order Brief created', details: 'Qty 600 pcs · Target ₹180 · SS25' },
    ],
  },
  // ── Lifecycle Stage: Vendor (RFQ Sent, Awaiting Responses) ──────────────────
  {
    id: 'NNKNTW250021',
    styleCode: 'NN322-088',
    styleName: 'Girls Floral Printed Dress',
    colour: 'PEACH',
    category: 'Wovens',
    product: 'Dress',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '2-6 Y',
    fabricQuality: 'Printed Cotton Voile',
    vendor: { id: 'v_tba', name: 'NOT ASSIGNED', location: '—' } as any,
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'vendor',
    atRisk: false,
    handoverDate: '2026-06-08',
    orderToVendorDate: '2026-05-15',
    buyingExpectedInwardDate: '2026-08-20',
    vendorPromisedDate: '2026-08-18',
    targetPrice: 265,
    costStatus: 'pending',
    orderQty: 400,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN322-088',
    rfqStatus: 'responded',
    vendorRFQs: [
      {
        id: 'rfq-001',
        subOrderId: 'NNKNTW250021',
        vendor: vendors[6],
        styleCode: 'NN322-088',
        styleName: 'Girls Floral Printed Dress',
        colour: 'PEACH',
        orderQty: 400,
        targetPrice: 265,
        handoverDate: '2026-06-08',
        fabricQuality: 'Printed Cotton Voile',
        category: 'Wovens',
        sizeRatio: '1:2:2:1',
        warehouseSplit: [{ warehouse: 'BHW', qty: 200 }, { warehouse: 'DEL', qty: 120 }, { warehouse: 'BLR', qty: 80 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN322-088',
        notes: 'Ensure floral print is centered. Refer tech pack page 4 for placement.',
        status: 'responded',
        sentAt: '2026-05-10T10:00:00',
        expiresAt: '2026-05-17T23:59:59',
        respondedAt: '2026-05-11T14:30:00',
        quotedPrice: 258,
        vendorPromisedDate: '2026-08-10',
        leadTimeDays: 60,
        capacityQty: 400,
      } as VendorRFQ,
      {
        id: 'rfq-002',
        subOrderId: 'NNKNTW250021',
        vendor: vendors[7],
        styleCode: 'NN322-088',
        styleName: 'Girls Floral Printed Dress',
        colour: 'PEACH',
        orderQty: 400,
        targetPrice: 265,
        handoverDate: '2026-06-08',
        fabricQuality: 'Printed Cotton Voile',
        category: 'Wovens',
        sizeRatio: '1:2:2:1',
        warehouseSplit: [{ warehouse: 'BHW', qty: 200 }, { warehouse: 'DEL', qty: 120 }, { warehouse: 'BLR', qty: 80 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN322-088',
        status: 'sent',
        sentAt: '2026-05-10T10:00:00',
        expiresAt: '2026-05-17T23:59:59',
      } as VendorRFQ,
      {
        id: 'rfq-003',
        subOrderId: 'NNKNTW250021',
        vendor: vendors[5],
        styleCode: 'NN322-088',
        styleName: 'Girls Floral Printed Dress',
        colour: 'PEACH',
        orderQty: 400,
        targetPrice: 265,
        handoverDate: '2026-06-08',
        fabricQuality: 'Printed Cotton Voile',
        category: 'Wovens',
        sizeRatio: '1:2:2:1',
        warehouseSplit: [{ warehouse: 'BHW', qty: 200 }, { warehouse: 'DEL', qty: 120 }, { warehouse: 'BLR', qty: 80 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN322-088',
        status: 'declined',
        sentAt: '2026-05-10T10:00:00',
        expiresAt: '2026-05-17T23:59:59',
        respondedAt: '2026-05-10T18:00:00',
        declineReason: 'Factory at full capacity until end of June.',
      } as VendorRFQ,
    ],
    history: [
      { id: 'h3', timestamp: '2026-05-10T10:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'RFQ sent', details: 'Sent to 3 vendors: Aditee International, Caarvi Textiles, And Design' },
      { id: 'h2', timestamp: '2026-05-08T11:30:00', actor: 'Rajesh Menon', actorRole: 'Sourcing Manager', action: 'Order assigned to POC', details: 'Assigned to Parthipan Kumar' },
      { id: 'h1', timestamp: '2026-05-06T09:00:00', actor: 'Megha Sharma', actorRole: 'Category Head', action: 'Order Brief created', details: 'Qty 400 pcs · Target ₹265 · SS25' },
    ],
  },
  // ── Lifecycle Stage: Assigned (POC assigned, RFQ not started) ────────────────
  {
    id: 'NNKNTW250032',
    styleCode: 'NN322-091',
    styleName: 'Boys Graphic Tee',
    colour: 'NAVY',
    category: 'Knits',
    product: 'Top',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-1',
    gender: 'Boys',
    ageGroup: '4-8 Y',
    fabricQuality: 'Reactive Printed Cotton Jersey',
    vendor: { id: 'v_tba', name: 'NOT ASSIGNED', location: '—' } as any,
    poc: currentUser,
    status: 'not-started',
    currentStage: 'assigned',
    atRisk: false,
    handoverDate: '2026-06-15',
    orderToVendorDate: '2026-05-25',
    buyingExpectedInwardDate: '2026-08-10',
    vendorPromisedDate: '2026-08-05',
    targetPrice: 195,
    costStatus: 'pending',
    orderQty: 750,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN322-091',
    rfqStatus: 'not-started',
    vendorRFQs: [],
    history: [
      { id: 'h2', timestamp: '2026-05-12T11:00:00', actor: 'Rajesh Menon', actorRole: 'Sourcing Manager', action: 'Order assigned to POC', details: 'Assigned to Parthipan Kumar' },
      { id: 'h1', timestamp: '2026-05-10T09:00:00', actor: 'Priya Sharma', actorRole: 'Buying POC', action: 'Order Brief created', details: 'Qty 750 pcs · Target ₹195 · SS25' },
    ],
  },
  // ── Vendor Assignment (RFQs Sent — awaiting responses) ──────────────────────
  {
    id: 'NNKNTW250018',
    styleCode: 'NN416-089',
    styleName: 'Girls Ruffle Neck Top',
    colour: 'MINT GREEN',
    category: 'Knits',
    product: 'Top',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Single Jersey',
    vendor: { id: 'v_tba', name: 'NOT ASSIGNED', location: '—' } as any,
    poc: currentUser,
    status: 'not-started',
    currentStage: 'vendor',
    atRisk: false,
    handoverDate: '2026-04-13',
    orderToVendorDate: '2026-05-15',
    buyingExpectedInwardDate: '2026-06-05',
    vendorPromisedDate: '2026-06-05',
    targetPrice: 220,
    costStatus: 'pending',
    orderQty: 500,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN416-089',
    rfqStatus: 'sent',
    vendorRFQs: [
      {
        id: 'rfq-018-1',
        subOrderId: 'NNKNTW250018',
        vendor: vendors[6],
        styleCode: 'NN416-089',
        styleName: 'Girls Ruffle Neck Top',
        colour: 'MINT GREEN',
        orderQty: 500,
        targetPrice: 220,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Single Jersey',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:2 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 500 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN416-089',
        status: 'sent',
        sentAt: '2026-05-15T10:00:00',
        expiresAt: '2026-05-22T18:00:00',
      },
      {
        id: 'rfq-018-2',
        subOrderId: 'NNKNTW250018',
        vendor: vendors[7],
        styleCode: 'NN416-089',
        styleName: 'Girls Ruffle Neck Top',
        colour: 'MINT GREEN',
        orderQty: 500,
        targetPrice: 220,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Single Jersey',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:2 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 500 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN416-089',
        status: 'sent',
        sentAt: '2026-05-15T10:00:00',
        expiresAt: '2026-05-22T18:00:00',
      },
      {
        id: 'rfq-018-3',
        subOrderId: 'NNKNTW250018',
        vendor: vendors[8],
        styleCode: 'NN416-089',
        styleName: 'Girls Ruffle Neck Top',
        colour: 'MINT GREEN',
        orderQty: 500,
        targetPrice: 220,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Single Jersey',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:2 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 500 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN416-089',
        status: 'sent',
        sentAt: '2026-05-15T10:00:00',
        expiresAt: '2026-05-22T18:00:00',
      },
    ],
    history: [
      { id: 'h2', timestamp: '2026-05-15T10:00:00', actor: 'Parthipan Kumar', actorRole: 'Sourcing POC', action: 'RFQs sent', details: 'Sent to 3 vendors' },
      { id: 'h1', timestamp: '2026-04-13T09:00:00', actor: 'Priya Sharma', actorRole: 'Buying POC', action: 'Order Brief created' },
    ],
  },
  // ── Vendor Assignment (Quotes Received — 1 responded, 1 awaiting, 1 declined) ─
  {
    id: 'NNKNTW250019',
    styleCode: 'NN419-201',
    styleName: 'Boys Printed Polo T-Shirt',
    colour: 'WHITE',
    category: 'Knits',
    product: 'T-Shirt',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-1',
    gender: 'Boys',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Blend Pique',
    vendor: { id: 'v_tba', name: 'NOT ASSIGNED', location: '—' } as any,
    poc: currentUser,
    status: 'not-started',
    currentStage: 'vendor',
    atRisk: false,
    handoverDate: '2026-04-13',
    orderToVendorDate: '2026-05-13',
    buyingExpectedInwardDate: '2026-06-10',
    vendorPromisedDate: '2026-06-10',
    targetPrice: 175,
    costStatus: 'pending',
    orderQty: 750,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN419-201',
    rfqStatus: 'responded',
    vendorRFQs: [
      {
        id: 'rfq-019-1',
        subOrderId: 'NNKNTW250019',
        vendor: vendors[6],
        styleCode: 'NN419-201',
        styleName: 'Boys Printed Polo T-Shirt',
        colour: 'WHITE',
        orderQty: 750,
        targetPrice: 175,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Blend Pique',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:3 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 750 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN419-201',
        status: 'responded',
        sentAt: '2026-05-13T10:00:00',
        expiresAt: '2026-05-20T18:00:00',
        respondedAt: '2026-05-14T15:30:00',
        quotedPrice: 168,
        vendorPromisedDate: '2026-08-12',
        leadTimeDays: 65,
        capacityQty: 750,
      },
      {
        id: 'rfq-019-2',
        subOrderId: 'NNKNTW250019',
        vendor: vendors[7],
        styleCode: 'NN419-201',
        styleName: 'Boys Printed Polo T-Shirt',
        colour: 'WHITE',
        orderQty: 750,
        targetPrice: 175,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Blend Pique',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:3 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 750 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN419-201',
        status: 'sent',
        sentAt: '2026-05-13T10:00:00',
        expiresAt: '2026-05-20T18:00:00',
      },
      {
        id: 'rfq-019-3',
        subOrderId: 'NNKNTW250019',
        vendor: vendors[8],
        styleCode: 'NN419-201',
        styleName: 'Boys Printed Polo T-Shirt',
        colour: 'WHITE',
        orderQty: 750,
        targetPrice: 175,
        handoverDate: '2026-04-13',
        fabricQuality: 'Cotton Blend Pique',
        category: 'Knits',
        sizeRatio: '4Y:1 / 5Y:2 / 6Y:3 / 7Y:2 / 8Y:1',
        warehouseSplit: [{ warehouse: 'BLR-WH', qty: 750 }],
        techPackUrl: 'https://drive.google.com/file/d/mock-tech-pack-NN419-201',
        status: 'declined',
        sentAt: '2026-05-13T10:00:00',
        expiresAt: '2026-05-20T18:00:00',
        respondedAt: '2026-05-14T11:00:00',
        declineReason: 'Capacity full — committed to other orders for May handover.',
      },
    ],
    history: [
      { id: 'h3', timestamp: '2026-05-14T15:30:00', actor: 'Aditi Sharma', actorRole: 'Vendor (ADITEE INTERNATIONAL)', action: 'RFQ Response', details: 'Quoted ₹168 · 750 pcs capacity · delivery 12 Aug' },
      { id: 'h2', timestamp: '2026-05-13T10:00:00', actor: 'Parthipan Kumar', actorRole: 'Sourcing POC', action: 'RFQs sent', details: 'Sent to 3 vendors' },
      { id: 'h1', timestamp: '2026-04-13T09:00:00', actor: 'Priya Sharma', actorRole: 'Buying POC', action: 'Order Brief created' },
    ],
  },
  // ── Lifecycle Stage: Costing (Vendor Not Submitted) ───────────────────────────
  {
    id: 'NNKNTW250022',
    styleCode: 'NN401-319',
    styleName: 'Boys Denim Look Shorts',
    colour: 'LIGHT BLUE',
    category: 'Wovens',
    product: 'Bottom',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-1',
    gender: 'Boys',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Denim / Twill',
    vendor: vendors[7],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'costing',
    atRisk: false,
    handoverDate: '2026-04-05',
    orderToVendorDate: '2026-04-10',
    buyingExpectedInwardDate: '2026-06-10',
    vendorPromisedDate: '2026-06-08',
    targetPrice: 240,
    costStatus: 'pending',
    orderQty: 250,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-10T10:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'Caarvi Textiles, Delhi' },
      { id: 'h2', timestamp: '2026-04-05T09:00:00', actor: 'Megha Sharma', actorRole: 'Category Head', action: 'Order Brief created' },
    ],
  },
  // ── Lifecycle Stage: Costing Submitted (Under Review) ────────────────────────
  {
    id: 'NNKNTW250023',
    styleCode: 'NN413-622',
    styleName: 'Girls Embroidered Kurta',
    colour: 'YELLOW',
    category: 'Wovens',
    product: 'Ethnic',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Cambric with Embroidery',
    vendor: vendors[9],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'costing',
    atRisk: false,
    handoverDate: '2026-04-02',
    orderToVendorDate: '2026-04-08',
    buyingExpectedInwardDate: '2026-06-05',
    vendorPromisedDate: '2026-06-03',
    targetPrice: 380,
    closedCost: 365,
    costStatus: 'submitted',
    orderQty: 200,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-14T15:00:00', actor: 'Swara Creation', actorRole: 'Vendor', action: 'Costing submitted', details: '₹365 per piece — within target ₹380' },
      { id: 'h2', timestamp: '2026-04-08T11:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'Swara Creation, Surat' },
    ],
  },
  // ── Lifecycle Stage: Costing Escalated (Above Target) ────────────────────────
  {
    id: 'NNKNTW250024',
    styleCode: 'NN321-447',
    styleName: 'Girls Net Party Gown',
    colour: 'RED',
    category: 'Wovens',
    product: 'Dress',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'HERO',
    gender: 'Girls',
    ageGroup: '2-8 Y',
    fabricQuality: 'Poly Net / Satin Lining',
    vendor: vendors[2],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'costing',
    atRisk: true,
    handoverDate: '2026-03-28',
    orderToVendorDate: '2026-04-03',
    buyingExpectedInwardDate: '2026-06-01',
    vendorPromisedDate: '2026-05-28',
    targetPrice: 450,
    closedCost: 492,
    costStatus: 'escalated',
    orderQty: 150,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-12T14:00:00', actor: 'Ahul Singh', actorRole: 'Sourcing Manager', action: 'Costing escalated to manager', details: '₹492 — ₹42 above target ₹450' },
      { id: 'h2', timestamp: '2026-04-10T10:00:00', actor: 'IDS Fashion', actorRole: 'Vendor', action: 'Costing submitted', details: '₹492 per piece — above target' },
      { id: 'h3', timestamp: '2026-04-03T09:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'IDS Fashion, Noida' },
    ],
  },
  // ── Lifecycle Stage: Pre-Prod Not Started, PO Not Raised ─────────────────────
  {
    id: 'NNKNTW250025',
    styleCode: 'NN311-203',
    styleName: 'Boys Solid Cotton Tee',
    colour: 'WHITE',
    category: 'Knits',
    product: 'Top',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Boys',
    ageGroup: '2-8 Y',
    fabricQuality: 'Single Jersey 180 GSM',
    vendor: vendors[4],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'pre-prod',
    atRisk: false,
    handoverDate: '2026-03-22',
    orderToVendorDate: '2026-03-30',
    buyingExpectedInwardDate: '2026-06-08',
    vendorPromisedDate: '2026-06-05',
    costingApprovedDate: '2026-04-08',
    targetPrice: 195,
    closedCost: 188,
    costStatus: 'approved',
    orderQty: 350,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'not-started', plannedDate: '2026-04-22', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'not-started', plannedDate: '2026-04-26', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'not-started', plannedDate: '2026-04-30', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'not-started', plannedDate: '2026-05-04', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'not-started', plannedDate: '2026-05-08', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'not-started', plannedDate: '2026-05-10', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'not-started', plannedDate: '2026-05-12', approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-08T10:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹188 ≤ ₹195 target · PP to commence' },
      { id: 'h2', timestamp: '2026-03-30T09:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'DIV Creations, Faridabad' },
    ],
  },
  // ── Lifecycle Stage: Pre-Prod Partial (Some Samples Done), PO Raised ─────────
  {
    id: 'NNKNTW250026',
    styleCode: 'NN413-811',
    styleName: 'Girls Printed Anarkali Kurta',
    colour: 'MULTI',
    category: 'Wovens',
    product: 'Ethnic',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Printed Rayon Crepe',
    vendor: vendors[6],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'pre-prod',
    atRisk: false,
    handoverDate: '2026-03-15',
    orderToVendorDate: '2026-03-22',
    buyingExpectedInwardDate: '2026-05-28',
    vendorPromisedDate: '2026-05-25',
    costingApprovedDate: '2026-03-30',
    targetPrice: 345,
    closedCost: 332,
    costStatus: 'approved',
    orderQty: 280,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0640M', qty: 160 },
      { warehouse: 'GUR', poNumber: 'PPO-0640S', qty: 120 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-04-05', actualDate: '2026-04-06', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-04-09', actualDate: '2026-04-10', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-04-13', actualDate: '2026-04-14', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'pending', plannedDate: '2026-04-17', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'not-started', plannedDate: '2026-04-21', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'not-started', plannedDate: '2026-04-24', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'not-started', plannedDate: '2026-04-26', approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-14T11:00:00', actor: 'Rekha P', actorRole: 'Fit Technician', action: 'Fit Sample approved' },
      { id: 'h2', timestamp: '2026-04-10T09:30:00', actor: 'Meena K', actorRole: 'Designer', action: 'Strike Off approved' },
      { id: 'h3', timestamp: '2026-04-06T10:00:00', actor: 'Meena K', actorRole: 'Designer', action: 'Lab Dip approved' },
      { id: 'h4', timestamp: '2026-03-30T09:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹332 ≤ ₹345 target' },
    ],
  },
  // ── Lifecycle Stage: Pre-Prod All Approved, PO Raised ────────────────────────
  {
    id: 'NNKNTW250027',
    styleCode: 'NN401-557',
    styleName: 'Boys Casual Shirt Set',
    colour: 'OLIVE',
    category: 'Wovens',
    product: 'Clothing Set',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'TIER-2',
    gender: 'Boys',
    ageGroup: '2-8 Y',
    fabricQuality: 'Cotton Poplin / Twill',
    vendor: vendors[8],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'pre-prod',
    atRisk: false,
    handoverDate: '2026-03-10',
    orderToVendorDate: '2026-03-18',
    buyingExpectedInwardDate: '2026-05-20',
    vendorPromisedDate: '2026-05-18',
    costingApprovedDate: '2026-03-25',
    targetPrice: 310,
    closedCost: 298,
    costStatus: 'approved',
    orderQty: 320,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0632M', qty: 180 },
      { warehouse: 'GUR', poNumber: 'PPO-0632S', qty: 140 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-04-01', actualDate: '2026-04-02', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-04-05', actualDate: '2026-04-06', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-04-08', actualDate: '2026-04-09', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-04-10', actualDate: '2026-04-11', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-04-13', actualDate: '2026-04-14', approvedBy: 'Meena K + Rekha P', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-04-15', actualDate: '2026-04-15', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-16', actualDate: '2026-04-16', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-16T15:00:00', actor: 'Rekha P', actorRole: 'Fit Technician', action: 'PP Fit approved — all pre-production complete' },
      { id: 'h2', timestamp: '2026-04-15T14:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'GPT approved' },
      { id: 'h3', timestamp: '2026-04-14T10:00:00', actor: 'Meena K + Rekha P', actorRole: 'Designer + Fit Tech', action: 'PP Sample (4B) approved' },
      { id: 'h4', timestamp: '2026-03-25T09:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹298 ≤ ₹310 target' },
    ],
  },
  // ── Lifecycle Stage: Production — PO Raised, Not Started ─────────────────────
  {
    id: 'NNKNTW250028',
    styleCode: 'NN413-390',
    styleName: 'Girls Lehenga Choli Set',
    colour: 'PINK GOLD',
    category: 'Wovens',
    product: 'Ethnic',
    season: 'SS25',
    orderType: 'NEW',
    tier: 'HERO',
    gender: 'Girls',
    ageGroup: '2-8 Y',
    fabricQuality: 'Poly Georgette / Net / Satin',
    vendor: vendors[5],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'production',
    atRisk: false,
    handoverDate: '2026-03-05',
    orderToVendorDate: '2026-03-12',
    buyingExpectedInwardDate: '2026-05-25',
    vendorPromisedDate: '2026-05-22',
    costingApprovedDate: '2026-03-20',
    targetPrice: 525,
    closedCost: 510,
    costStatus: 'approved',
    orderQty: 180,
    cutQty: 0, sewingQty: 0, packedQty: 0, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0618M', qty: 100 },
      { warehouse: 'GUR', poNumber: 'PPO-0618S', qty: 80 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-22', actualDate: '2026-03-23', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-03-26', actualDate: '2026-03-27', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-03-30', actualDate: '2026-03-31', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-04-02', actualDate: '2026-04-03', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-04-05', actualDate: '2026-04-06', approvedBy: 'Meena K + Rekha P', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-04-07', actualDate: '2026-04-07', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-08', actualDate: '2026-04-09', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
    ],
    productionHistory: [],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-09T10:00:00', actor: 'Rekha P', actorRole: 'Fit Technician', action: 'PP Fit approved — production cleared to begin' },
      { id: 'h2', timestamp: '2026-03-20T09:00:00', actor: 'System', actorRole: 'Auto', action: 'Costing auto-approved', details: '₹510 ≤ ₹525 target' },
      { id: 'h3', timestamp: '2026-03-12T10:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'Vendor assigned', details: 'AND DESIGN, Jaipur' },
    ],
  },
  // ── Lifecycle Stage: FI — Production Complete, FI Not Requested ──────────────
  {
    id: 'NNKNTW250029',
    styleCode: 'NN311-922',
    styleName: 'Boys Hooded Sweatshirt Set',
    colour: 'ROYAL BLUE',
    category: 'Knits',
    product: 'Clothing Set',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Boys',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Fleece / French Terry',
    vendor: vendors[1],
    poc: currentUser,
    status: 'needs-attention',
    currentStage: 'fi',
    atRisk: false,
    handoverDate: '2026-02-20',
    orderToVendorDate: '2026-02-28',
    buyingExpectedInwardDate: '2026-05-10',
    vendorPromisedDate: '2026-05-08',
    costingApprovedDate: '2026-03-08',
    targetPrice: 380,
    closedCost: 365,
    costStatus: 'approved',
    orderQty: 320,
    cutQty: 328, sewingQty: 322, packedQty: 315, fiQty: 0, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0595M', qty: 180 },
      { warehouse: 'GUR', poNumber: 'PPO-0595S', qty: 140 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-10', actualDate: '2026-03-11', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-03-14', actualDate: '2026-03-15', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-03-18', actualDate: '2026-03-19', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-03-22', actualDate: '2026-03-23', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-03-26', actualDate: '2026-03-27', approvedBy: 'Meena K + Rekha P', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-03-29', actualDate: '2026-03-29', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-04-01', actualDate: '2026-04-01', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
    ],
    productionHistory: [
      { date: '2026-04-14', cutQty: 328, sewingQty: 322, packedQty: 315, updatedBy: 'Arihant Fashions' },
      { date: '2026-04-11', cutQty: 300, sewingQty: 290, packedQty: 250, updatedBy: 'Arihant Fashions' },
      { date: '2026-04-08', cutQty: 240, sewingQty: 220, packedQty: 180, updatedBy: 'Arihant Fashions' },
    ],
    fiRequests: [],
    history: [
      { id: 'h1', timestamp: '2026-04-14T16:30:00', actor: 'Arihant Fashions', actorRole: 'Vendor', action: 'Production complete — 315 pcs packed', details: 'FI to be raised by POC' },
      { id: 'h2', timestamp: '2026-04-01T10:00:00', actor: 'Rekha P', actorRole: 'Fit Technician', action: 'PP Fit approved' },
    ],
  },
  // ── Lifecycle Stage: FI In Progress ──────────────────────────────────────────
  {
    id: 'NNKNTW250030',
    styleCode: 'NN413-274',
    styleName: 'Girls Denim Jacket Set',
    colour: 'INDIGO',
    category: 'Wovens',
    product: 'Jacket Set',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-1',
    gender: 'Girls',
    ageGroup: '4-8 Y',
    fabricQuality: 'Cotton Denim / Rib',
    vendor: vendors[3],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'fi',
    atRisk: false,
    handoverDate: '2026-02-15',
    orderToVendorDate: '2026-02-22',
    buyingExpectedInwardDate: '2026-05-05',
    vendorPromisedDate: '2026-05-03',
    costingApprovedDate: '2026-03-01',
    targetPrice: 420,
    closedCost: 405,
    costStatus: 'approved',
    orderQty: 240,
    cutQty: 245, sewingQty: 242, packedQty: 238, fiQty: 230, dispatchedQty: 0, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0588M', qty: 140 },
      { warehouse: 'GUR', poNumber: 'PPO-0588S', qty: 100 },
    ],
    preProdStages: [
      { id: 'pp1', name: 'Lab Dip', status: 'approved', plannedDate: '2026-03-05', actualDate: '2026-03-06', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp2', name: 'Strike Off', status: 'approved', plannedDate: '2026-03-10', actualDate: '2026-03-11', approvedBy: 'Meena K', approverRole: 'Designer' },
      { id: 'pp3', name: 'Fit Sample', status: 'approved', plannedDate: '2026-03-14', actualDate: '2026-03-15', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
      { id: 'pp4', name: 'Fabric Inward (FD Status)', status: 'approved', plannedDate: '2026-03-18', actualDate: '2026-03-19', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp5', name: 'PP Sample (4B / Commercial)', status: 'approved', plannedDate: '2026-03-22', actualDate: '2026-03-23', approvedBy: 'Meena K + Rekha P', approverRole: 'Designer + Fit Tech' },
      { id: 'pp6', name: 'GPT (Garment Processing Test)', status: 'approved', plannedDate: '2026-03-25', actualDate: '2026-03-25', approvedBy: 'Parthipan Kumar', approverRole: 'POC' },
      { id: 'pp7', name: 'PP Fit', status: 'approved', plannedDate: '2026-03-27', actualDate: '2026-03-27', approvedBy: 'Rekha P', approverRole: 'Fit Technician' },
    ],
    productionHistory: [
      { date: '2026-04-12', cutQty: 245, sewingQty: 242, packedQty: 238, updatedBy: 'BS Fashion' },
      { date: '2026-04-08', cutQty: 220, sewingQty: 210, packedQty: 185, updatedBy: 'BS Fashion' },
    ],
    fiRequests: [
      { id: 'fi1', requestedDate: '2026-04-13', scheduledDate: '2026-04-15', assignedInspector: 'Nimain Das', status: 'in-progress', fiQty: 230, location: 'Kolkata Factory', round: 1 },
    ],
    history: [
      { id: 'h1', timestamp: '2026-04-13T14:00:00', actor: 'Parthipan Kumar', actorRole: 'POC', action: 'FI requested', details: '230 pcs — Nimain Das assigned' },
      { id: 'h2', timestamp: '2026-04-12T16:00:00', actor: 'BS Fashion', actorRole: 'Vendor', action: 'Production complete — 238 pcs packed' },
    ],
  },
  // ── Lifecycle Stage: ASN Raised ───────────────────────────────────────────────
  {
    id: 'NNKNTW250031',
    styleCode: 'NN401-688',
    styleName: 'Boys Solid Polo T-Shirt',
    colour: 'BOTTLE GREEN',
    category: 'Knits',
    product: 'Top',
    season: 'SS25',
    orderType: 'REPLEN',
    tier: 'TIER-2',
    gender: 'Boys',
    ageGroup: '4-8 Y',
    fabricQuality: 'Pique 220 GSM',
    vendor: vendors[0],
    poc: currentUser,
    status: 'on-track',
    currentStage: 'asn',
    atRisk: false,
    handoverDate: '2026-02-05',
    orderToVendorDate: '2026-02-12',
    buyingExpectedInwardDate: '2026-04-28',
    vendorPromisedDate: '2026-04-26',
    costingApprovedDate: '2026-02-20',
    targetPrice: 220,
    closedCost: 210,
    costStatus: 'approved',
    orderQty: 500,
    cutQty: 512, sewingQty: 508, packedQty: 498, fiQty: 492, dispatchedQty: 492, grnQty: 0,
    poNumbers: [
      { warehouse: 'MUM', poNumber: 'PPO-0575M', qty: 280 },
      { warehouse: 'GUR', poNumber: 'PPO-0575S', qty: 220 },
    ],
    preProdStages: [],
    productionHistory: [],
    fiRequests: [
      { id: 'fi1', requestedDate: '2026-04-08', scheduledDate: '2026-04-09', assignedInspector: 'Rishabh Sharma', status: 'pass', fiQty: 492, location: 'Faridabad Factory', result: 'pass', round: 1 },
    ],
    history: [
      { id: 'h1', timestamp: '2026-04-14T10:00:00', actor: 'Ramesh Singh', actorRole: 'Warehouse Ops', action: 'ASN received — goods in transit', details: '492 pcs dispatched from Faridabad' },
      { id: 'h2', timestamp: '2026-04-09T15:00:00', actor: 'Rishabh Sharma', actorRole: 'QA Inspector', action: 'FI passed — 492 pcs cleared' },
    ],
  },
]

// ─── Queue Items ──────────────────────────────────────────────────────────────

export const queueItems: QueueItem[] = [
  {
    subOrderId: 'NNKNTW250001',
    styleCode: 'NN401-238',
    colour: 'CORAL',
    vendorName: 'BHARTI APPARELS',
    actionType: 'production-update-overdue',
    actionLabel: 'Vendor production update overdue — last updated 2 days ago',
    urgency: 'overdue',
    daysOverdue: 2,
    ctaLabel: 'Update Now',
    ctaRoute: '/portfolio/NNKNTW250001?tab=production',
  },
  {
    subOrderId: 'NNKNTW250002',
    styleCode: 'NN413-185',
    colour: 'BLUE WHITE',
    vendorName: 'ARIHANT FASHIONS',
    actionType: 'sample-approval-pending',
    actionLabel: 'PP Sample (Pre-Production) approval pending — planned Apr 10, overdue 4 days',
    urgency: 'overdue',
    daysOverdue: 4,
    ctaLabel: 'Review Sample',
    ctaRoute: '/portfolio/NNKNTW250002?tab=pre-prod',
  },
  {
    subOrderId: 'NNKNTW250003',
    styleCode: 'NN321-099',
    colour: 'YELLOW',
    vendorName: 'IDS FASHION',
    actionType: 'fi-needed',
    actionLabel: 'Final Inspection not yet requested — packing 100% complete (385 units)',
    urgency: 'overdue',
    daysOverdue: 1,
    ctaLabel: 'Raise FI',
    ctaRoute: '/portfolio/NNKNTW250003?tab=inspection',
  },
  {
    subOrderId: 'NNKNTW250004',
    styleCode: 'NN411-715',
    colour: 'PINK',
    vendorName: 'BS FASHION',
    actionType: 'pre-prod-overdue',
    actionLabel: 'Lab Dip submission planned today — awaiting dispatch from vendor',
    urgency: 'due-today',
    ctaLabel: 'Update Stage',
    ctaRoute: '/portfolio/NNKNTW250004?tab=pre-prod',
  },
  {
    subOrderId: 'NNKNTW250005',
    styleCode: 'NN413-438',
    colour: 'GREEN',
    vendorName: 'DIV CREATIONS',
    actionType: 'costing-due',
    actionLabel: 'Costing submission due — target ₹285, vendor yet to submit',
    urgency: 'due-today',
    ctaLabel: 'Submit Costing',
    ctaRoute: '/portfolio/NNKNTW250005?tab=costing',
  },
  {
    subOrderId: 'NNKNTW250006',
    styleCode: 'NN401-802',
    colour: 'WHITE',
    vendorName: 'AND DESIGN',
    actionType: 'production-update-overdue',
    actionLabel: 'Production update due — no update received today',
    urgency: 'due-today',
    ctaLabel: 'Update Now',
    ctaRoute: '/portfolio/NNKNTW250006?tab=production',
  },
]

// ─── Notifications ────────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  { id: 'n1', type: 'overdue', subOrderId: 'NNKNTW250001', message: 'NNKNTW250001 · Production update overdue 2 days', timestamp: '2026-04-14T09:00:00', read: false },
  { id: 'n2', type: 'due-today', subOrderId: 'NNKNTW250005', message: 'NNKNTW250005 · Costing submission due today', timestamp: '2026-04-14T08:30:00', read: false },
  { id: 'n3', type: 'overdue', subOrderId: 'NNKNTW250003', message: 'NNKNTW250003 · FI not raised — packing complete', timestamp: '2026-04-13T18:00:00', read: false },
  { id: 'n4', type: 'completed', subOrderId: 'NNKNTW250012', message: 'NNKNTW250012 · GRN confirmed — 390 units received', timestamp: '2026-04-13T15:45:00', read: false },
  { id: 'n5', type: 'due-today', message: '3 pre-production stages due today across 2 SubOrders', timestamp: '2026-04-14T08:00:00', read: false },
  { id: 'n6', type: 'overdue', subOrderId: 'NNKNTW250002', message: 'NNKNTW250002 · PP Sample pending approval 4 days', timestamp: '2026-04-13T09:00:00', read: true },
  { id: 'n7', type: 'info', subOrderId: 'NNKNTW250014', message: 'Costing auto-approved: NNKNTW250014 · ₹308 ≤ ₹320 target', timestamp: '2026-04-12T16:30:00', read: true },
  { id: 'n8', type: 'due-today', subOrderId: 'NNKNTW250009', message: 'NNKNTW250009 · FI request ready to raise', timestamp: '2026-04-12T11:00:00', read: true },
]
